# Generated by Django 5.1.3 on 2025-09-22 19:52

import django.db.models.deletion
import shortuuid.django_fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Jogador',
            fields=[
                ('id', shortuuid.django_fields.ShortUUIDField(alphabet=None, length=8, max_length=40, prefix='', primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100)),
                ('telefone', models.CharField(blank=True, max_length=20, null=True)),
                ('jogos', models.IntegerField(default=0)),
                ('vitorias', models.IntegerField(default=0, verbose_name='Vitórias')),
                ('derrotas', models.IntegerField(default=0)),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('criado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jogadores_criados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Jogador',
                'verbose_name_plural': 'Jogadores',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Dupla',
            fields=[
                ('id', shortuuid.django_fields.ShortUUIDField(alphabet=None, length=8, max_length=40, prefix='', primary_key=True, serialize=False)),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('criado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='duplas_criadas', to=settings.AUTH_USER_MODEL)),
                ('jogador1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='jogador1', to='cup.jogador', verbose_name='Jogador 1')),
                ('jogador2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='jogador2', to='cup.jogador', verbose_name='Jogador 2')),
            ],
            options={
                'verbose_name': 'Dupla',
                'verbose_name_plural': 'Duplas',
                'ordering': ['jogador1__nome'],
            },
        ),
        migrations.CreateModel(
            name='Ranking',
            fields=[
                ('id', shortuuid.django_fields.ShortUUIDField(alphabet=None, length=8, max_length=40, prefix='', primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100)),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('criado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rankings_criados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Ranking',
                'verbose_name_plural': 'Rankings',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Torneio',
            fields=[
                ('id', shortuuid.django_fields.ShortUUIDField(alphabet=None, length=8, max_length=40, prefix='', primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100)),
                ('data', models.DateField()),
                ('quantidade_grupos', models.IntegerField(choices=[(1, '1'), (2, '2'), (4, '4'), (8, '8')], default=2, help_text='\n            Selecione o número de grupos para distribuir as duplas\n            <ul>\n                <li>1 grupo: Fase de grupo e FINAL</li>\n                <li>2 grupos: Fase de grupo, SEMIFINAIS e FINAL</li>\n                <li>4 grupos: Fase de grupo, QUARTAS, SEMIFINAIS e FINAL</li>\n                <li>8 grupos: Fase de grupo, OITAVAS, QUARTAS, SEMIFINAIS e FINAL</li>\n            </ul>\n        ', verbose_name='Nº grupos')),
                ('tipo', models.CharField(choices=[('S', 'Simples'), ('D', 'Duplas')], default='D', help_text='Simples ou Duplas', max_length=1, verbose_name='Tipo de Torneio')),
                ('playoffs', models.BooleanField(default=True, help_text='Ativar para criar jogos de playoffs (OITAVAS, QUARTAS, SEMIFINAIS e FINAL)', verbose_name='Playoffs')),
                ('terceiro_lugar', models.BooleanField(default=False, help_text='É necessário 2 grupos ou mais.', verbose_name='Terceiro lugar')),
                ('open', models.BooleanField(default=False, help_text='Ativar para criar jogos manualmente (Apenas um grupo, sem playoffs)', verbose_name='Criar jogos manualmente')),
                ('slug', models.SlugField(unique=True)),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('criado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='torneios', to=settings.AUTH_USER_MODEL)),
                ('ranking', models.ForeignKey(blank=True, help_text='Agrupar torneio em um ranking', null=True, on_delete=django.db.models.deletion.SET_NULL, to='cup.ranking')),
            ],
            options={
                'verbose_name': 'Torneio',
                'verbose_name_plural': 'Torneios',
                'ordering': ['-data'],
            },
        ),
        migrations.CreateModel(
            name='Jogo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pontos_dupla1', models.IntegerField(blank=True, null=True, verbose_name='Pontos dupla 1')),
                ('pontos_dupla2', models.IntegerField(blank=True, null=True, verbose_name='Pontos dupla 2')),
                ('fase', models.CharField(blank=True, choices=[('GRUPO 1', 'G1'), ('GRUPO 2', 'G2'), ('GRUPO 3', 'G3'), ('GRUPO 4', 'G4'), ('OITAVAS', 'OF'), ('QUARTAS', 'QF'), ('SEMIFINAIS', 'SF'), ('FINAL', 'F'), ('TERCEIRO LUGAR', 'T'), ('CAMPEAO', 'C')], default='GRUPO 1', max_length=100, null=True, verbose_name='Fase')),
                ('concluido', models.CharField(choices=[('P', '🚫'), ('A', '🎾'), ('C', '✅')], default='P', max_length=2, verbose_name='Status')),
                ('obs', models.TextField(blank=True, help_text='Alguma observação sobre o jogo. Ex: "Dupla 1 WO"', null=True)),
                ('dupla1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dupla1', to='cup.dupla', verbose_name='Dupla 1')),
                ('dupla2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dupla2', to='cup.dupla', verbose_name='Dupla 2')),
                ('vencedor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cup.dupla', verbose_name='Vencedor')),
                ('torneio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cup.torneio', verbose_name='Torneio')),
            ],
        ),
        migrations.AddField(
            model_name='dupla',
            name='torneio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='duplas', to='cup.torneio'),
        ),
    ]
