# Generated by Django 5.1.3 on 2025-09-28 18:30

from django.db import migrations, models
from django.template.defaultfilters import slugify

def populate_slug(apps, schema_editor):
    Ranking = apps.get_model('cup', 'ranking')
    for ranking in Ranking.objects.all():
        if not ranking.slug:
            ranking.slug = f'{slugify(ranking.nome)}_{ranking.id}'
            ranking.save()

class Migration(migrations.Migration):

    dependencies = [
        ('cup', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ranking',
            name='slug',
            field=models.SlugField(null=True, blank=True, unique=True),
        ),
        migrations.RunPython(populate_slug, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='ranking',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
