# Generated by Django 5.1.3 on 2025-10-27 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cup', '0002_ranking_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='torneio',
            name='draw_pairs',
            field=models.BooleanField(default=False, help_text='Ativar para sortear duplas com jogadores cadastrados', verbose_name='Embaralhar duplas'),
        ),
    ]
