# Generated by Django 5.1.3 on 2025-11-17 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cup', '0003_torneio_draw_pairs'),
    ]

    operations = [
        migrations.AddField(
            model_name='torneio',
            name='inscricao_aberta',
            field=models.BooleanField(default=False, help_text='Criar um link para cadastrar jogadores no torneio', verbose_name='Inscrição aberta'),
        ),
        migrations.AlterField(
            model_name='torneio',
            name='draw_pairs',
            field=models.BooleanField(default=False, help_text='Ativar para sortear duplas com jogadores cadastrados', verbose_name='Sortear duplas'),
        ),
    ]
