# Generated by Django 5.1.3 on 2025-12-16 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cup', '0004_torneio_inscricao_aberta_alter_torneio_draw_pairs'),
    ]

    operations = [
        migrations.AddField(
            model_name='jogador',
            name='cpf',
            field=models.CharField(blank=True, max_length=11, null=True),
        ),
    ]
