# Generated by Django 5.1.3 on 2026-02-17 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cup', '0005_jogador_cpf'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='torneio',
            options={'ordering': ['-data', '-criado_em'], 'verbose_name': 'Torneio', 'verbose_name_plural': 'Torneios'},
        ),
    ]
