# Generated by Django 5.1.3 on 2026-03-15 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cup', '0006_alter_torneio_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='jogo',
            name='playoff_number',
            field=models.SmallIntegerField(blank=True, null=True, verbose_name='Playoff game number'),
        ),
        migrations.AlterField(
            model_name='jogo',
            name='fase',
            field=models.CharField(blank=True, choices=[('GRUPO 1', 'G1'), ('GRUPO 2', 'G2'), ('GRUPO 3', 'G3'), ('GRUPO 4', 'G4'), ('GRUPO 5', 'G5'), ('GRUPO 6', 'G6'), ('GRUPO 7', 'G7'), ('GRUPO 8', 'G8'), ('OITAVAS', 'OF'), ('QUARTAS', 'QF'), ('SEMIFINAIS', 'SF'), ('FINAL', 'F'), ('TERCEIRO LUGAR', 'T'), ('CAMPEAO', 'C')], default='GRUPO 1', max_length=100, null=True, verbose_name='Fase'),
        ),
        migrations.AlterField(
            model_name='torneio',
            name='quantidade_grupos',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8')], default=2, help_text='\n            Selecione o número de grupos para distribuir as duplas\n            <ul>\n                <li>1 grupo: Fase de grupo e FINAL</li>\n                <li>2 grupos: Fase de grupo, SEMIFINAIS e FINAL</li>\n                <li>3 ou 4 grupos: Fase de grupo, QUARTAS, SEMIFINAIS e FINAL</li>\n                <li>5, 6, 7 ou 8 grupos: Fase de grupo, OITAVAS, QUARTAS, SEMIFINAIS e FINAL</li>\n            </ul>\n        ', verbose_name='Nº grupos'),
        ),
    ]
