# Generated by Django 5.1.3 on 2026-03-16 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cup', '0007_jogo_playoff_number_alter_jogo_fase_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jogo',
            name='playoff_help_text',
            field=models.CharField(blank=True, help_text='Ex: 1 G1 x 2 G2, 1 G2 x BYE', max_length=100, null=True, verbose_name='Texto de ajuda para o playoff'),
        ),
        migrations.AlterField(
            model_name='torneio',
            name='draw_pairs',
            field=models.BooleanField(default=False, help_text='Duplas montadas aleatoriamente ao criar os jogos', verbose_name='Duplas aleatórias'),
        ),
    ]
