# Generated by Django 5.1.3 on 2026-03-19 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cup', '0008_jogo_playoff_help_text_alter_torneio_draw_pairs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jogo',
            name='playoff_help_text',
            field=models.CharField(blank=True, default='', help_text='Ex: 1º G1x2º G2, 1º G2xBYE', max_length=100, verbose_name='Texto de ajuda para o playoff'),
        ),
    ]
