# Generated by Django 5.1.3 on 2024-12-16 21:41

import django.db.models.deletion
import shortuuid.django_fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Quadra',
            fields=[
                ('id', shortuuid.django_fields.ShortUUIDField(alphabet=None, length=8, max_length=40, prefix='', primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100, verbose_name='Nome da Quadra')),
                ('tipo', models.CharField(choices=[('ABERTA', 'Aberta'), ('COBERTA', 'Coberta')], default='ABERTA', max_length=20, verbose_name='Tipo de Quadra')),
                ('preco_hora', models.DecimalField(decimal_places=2, default=60.0, max_digits=10, verbose_name='Preço por Hora')),
                ('disponivel', models.BooleanField(default=True, verbose_name='Disponível')),
            ],
            options={
                'verbose_name': 'Quadra',
                'verbose_name_plural': 'Quadras',
            },
        ),
        migrations.CreateModel(
            name='Aluguel',
            fields=[
                ('id', shortuuid.django_fields.ShortUUIDField(alphabet=None, length=8, max_length=40, prefix='', primary_key=True, serialize=False)),
                ('data', models.DateField(auto_now_add=True)),
                ('inicio', models.TimeField(verbose_name='Início')),
                ('fim', models.TimeField(verbose_name='Término')),
                ('cliente_nome', models.CharField(max_length=100, verbose_name='Nome do Cliente')),
                ('cliente_telefone', models.CharField(max_length=15, verbose_name='Telefone do Cliente')),
                ('valor_total', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor Total')),
                ('pago', models.BooleanField(default=False, verbose_name='Pago')),
                ('quadra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alugueis', to='aluguel_quadra.quadra', verbose_name='Quadra')),
            ],
            options={
                'verbose_name': 'Aluguel',
                'verbose_name_plural': 'Aluguéis',
            },
        ),
    ]
