# Generated by Django 5.1.3 on 2024-12-07 15:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Dupla',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jogador1', models.CharField(max_length=100)),
                ('jogador2', models.CharField(max_length=100)),
                ('telefone', models.CharField(blank=True, max_length=20, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('ativo', models.BooleanField(default=True)),
                ('criado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Dupla',
                'verbose_name_plural': 'Duplas',
                'ordering': ['jogador1', 'jogador2'],
            },
        ),
        migrations.CreateModel(
            name='Torneio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('data', models.DateField()),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('ativo', models.BooleanField(default=True)),
                ('criado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='torneios_criados', to=settings.AUTH_USER_MODEL)),
                ('duplas', models.ManyToManyField(blank=True, to='bt_cup.dupla')),
            ],
        ),
        migrations.CreateModel(
            name='Jogo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placar_dupla1', models.IntegerField(blank=True, null=True, verbose_name='')),
                ('placar_dupla2', models.IntegerField(blank=True, null=True, verbose_name='')),
                ('fase', models.CharField(blank=True, max_length=100, null=True)),
                ('concluido', models.BooleanField(default=False)),
                ('obs', models.TextField(blank=True, help_text='Alguma observação sobre o jogo. Ex: "Dupla 1 WO"', null=True)),
                ('dupla1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dupla1', to='bt_cup.dupla', verbose_name='Dupla 1')),
                ('dupla2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dupla2', to='bt_cup.dupla', verbose_name='Dupla 2')),
                ('torneio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bt_cup.torneio')),
            ],
        ),
    ]
