# Generated by Django 5.1.3 on 2024-12-16 21:31

import shortuuid.django_fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bt_cup', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dupla',
            name='id',
            field=shortuuid.django_fields.ShortUUIDField(alphabet=None, length=8, max_length=40, prefix='', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='torneio',
            name='id',
            field=shortuuid.django_fields.ShortUUIDField(alphabet=None, length=8, max_length=40, prefix='', primary_key=True, serialize=False),
        ),
    ]
