# Generated by Django 5.1.3 on 2024-12-31 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bt_cup', '0002_alter_dupla_id_alter_torneio_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='torneio',
            name='ativo',
            field=models.BooleanField(default=True, verbose_name='Ativo'),
        ),
    ]
