# Generated by Django 5.1.3 on 2025-02-22 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bt_cup', '0004_torneio_quantidade_grupos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dupla',
            name='jogador1',
            field=models.CharField(max_length=100, verbose_name='Jogador 1'),
        ),
        migrations.AlterField(
            model_name='dupla',
            name='jogador2',
            field=models.CharField(max_length=100, verbose_name='Jogador 2'),
        ),
        migrations.AlterField(
            model_name='jogo',
            name='concluido',
            field=models.BooleanField(default=False, verbose_name='Concluído'),
        ),
        migrations.AlterField(
            model_name='torneio',
            name='quantidade_grupos',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (4, '4'), (8, '8')], default=2, help_text='\n            Selecione o número de grupos para distribuir as duplas\n            <ul>\n                <li>1 grupo: Fase de grupo e FINAL</li>\n                <li>2 grupos: Fase de grupo, SEMIFINAIS e FINAL</li>\n                <li>4 grupos: Fase de grupo, QUARTAS, SEMIFINAIS e FINAL</li>\n                <li>8 grupos: Fase de grupo, OITAVAS, QUARTAS, SEMIFINAIS e FINAL</li>\n            </ul>\n        ', verbose_name='Nº grupos'),
        ),
    ]
