# Generated by Django 5.1.3 on 2025-03-05 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bt_cup', '0005_alter_dupla_jogador1_alter_dupla_jogador2_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='torneio',
            options={'ordering': ['-data'], 'verbose_name': 'Torneio', 'verbose_name_plural': 'Torneios'},
        ),
        migrations.AlterField(
            model_name='dupla',
            name='ativo',
            field=models.BooleanField(default=True, verbose_name='Ativo'),
        ),
    ]
