# Generated by Django 5.1.3 on 2025-08-10 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bt_cup', '0006_alter_torneio_options_alter_dupla_ativo'),
    ]

    operations = [
        migrations.AddField(
            model_name='torneio',
            name='playoffs',
            field=models.BooleanField(default=True, help_text='Ativar para criar jogos de playoffs (Oitavas, Quartas, Semifinais e Final)', verbose_name='Playoffs'),
        ),
        migrations.AlterField(
            model_name='jogo',
            name='concluido',
            field=models.BooleanField(default=False, verbose_name=''),
        ),
    ]
