# Generated by Django 5.1.3 on 2025-08-11 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bt_cup', '0007_torneio_playoffs_alter_jogo_concluido'),
    ]

    operations = [
        migrations.AddField(
            model_name='torneio',
            name='open',
            field=models.BooleanField(default=False, help_text='Atiar para criar jogos criados manualmente', verbose_name='Torneio aberto'),
        ),
        migrations.AlterField(
            model_name='torneio',
            name='playoffs',
            field=models.BooleanField(default=True, help_text='Ativar para criar jogos de playoffs (OITAVAS, QUARTAS, SEMIFINAIS e FINAL)', verbose_name='Playoffs'),
        ),
    ]
