# Generated by Django 5.1.3 on 2025-08-19 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bt_cup', '0008_torneio_open_alter_torneio_playoffs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jogo',
            name='fase',
            field=models.CharField(blank=True, choices=[('GRUPO 1', 'G1'), ('GRUPO 2', 'G2'), ('GRUPO 3', 'G3'), ('GRUPO 4', 'G4'), ('OITAVAS', 'OF'), ('QUARTAS', 'QF'), ('SEMIFINAIS', 'SF'), ('FINAL', 'F'), ('CAMPEAO', 'C')], default='GRUPO 1', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='torneio',
            name='open',
            field=models.BooleanField(default=False, help_text='Ativar para criar jogos manualmente (Apenas um grupo, sem playoffs)', verbose_name='Torneio aberto'),
        ),
    ]
