# Generated by Django 5.1.3 on 2025-08-19 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bt_cup', '0009_alter_jogo_fase_alter_torneio_open'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jogo',
            name='concluido',
            field=models.CharField(choices=[('P', 'Pendente'), ('A', 'Em Andamento'), ('C', 'Concluído')], default='P', max_length=2, verbose_name=''),
        ),
    ]
