# Generated by Django 5.1.3 on 2025-08-28 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bt_cup', '0010_alter_jogo_concluido'),
    ]

    operations = [
        migrations.AddField(
            model_name='torneio',
            name='terceiro_lugar',
            field=models.BooleanField(default=False, verbose_name='Disputa de terceiro lugar'),
        ),
        migrations.AlterField(
            model_name='jogo',
            name='concluido',
            field=models.CharField(choices=[('P', '❌'), ('A', '⌛'), ('C', '✅')], default='P', max_length=2, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='jogo',
            name='fase',
            field=models.CharField(blank=True, choices=[('GRUPO 1', 'G1'), ('GRUPO 2', 'G2'), ('GRUPO 3', 'G3'), ('GRUPO 4', 'G4'), ('OITAVAS', 'OF'), ('QUARTAS', 'QF'), ('SEMIFINAIS', 'SF'), ('FINAL', 'F'), ('TERCEIRO LUGAR', 'T'), ('CAMPEAO', 'C')], default='GRUPO 1', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='torneio',
            name='open',
            field=models.BooleanField(default=False, help_text='Ativar para criar jogos manualmente (Apenas um grupo, sem playoffs)', verbose_name='Criar jogos manualmente'),
        ),
    ]
