# Generated by Django 5.1.3 on 2025-09-11 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bt_cup', '0011_torneio_terceiro_lugar_alter_jogo_concluido_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='torneio',
            name='terceiro_lugar',
            field=models.BooleanField(default=False, help_text='É necessário 2 grupos ou mais.', verbose_name='Terceiro lugar'),
        ),
    ]
