# Generated by Django 5.1.3 on 2025-09-28 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bt_cup', '0013_torneio_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jogo',
            name='concluido',
            field=models.CharField(choices=[('P', '🚫'), ('A', '🎾'), ('C', '✅')], default='P', max_length=2, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='jogo',
            name='placar_dupla1',
            field=models.IntegerField(blank=True, null=True, verbose_name='Pontos dupla 1'),
        ),
        migrations.AlterField(
            model_name='jogo',
            name='placar_dupla2',
            field=models.IntegerField(blank=True, null=True, verbose_name='Pontos dupla 2'),
        ),
    ]
