# Generated by Django 5.1.3 on 2026-03-19 03:29

import django.db.models.deletion
import shortuuid.django_fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Jogador',
            fields=[
                ('id', shortuuid.django_fields.ShortUUIDField(alphabet=None, length=8, max_length=40, prefix='', primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100)),
                ('cpf', models.CharField(blank=True, max_length=11, null=True)),
                ('telefone', models.CharField(blank=True, max_length=20, null=True)),
                ('jogos', models.IntegerField(default=0)),
                ('vitorias', models.IntegerField(default=0, verbose_name='Vitórias')),
                ('derrotas', models.IntegerField(default=0)),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('criado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jogadores_futevolei_criados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Jogador',
                'verbose_name_plural': 'Jogadores',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Dupla',
            fields=[
                ('id', shortuuid.django_fields.ShortUUIDField(alphabet=None, length=8, max_length=40, prefix='', primary_key=True, serialize=False)),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('criado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='duplas_futevolei_criadas', to=settings.AUTH_USER_MODEL)),
                ('jogador1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='jogador1', to='futevolei.jogador', verbose_name='Jogador 1')),
                ('jogador2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='jogador2', to='futevolei.jogador', verbose_name='Jogador 2')),
            ],
            options={
                'verbose_name': 'Dupla',
                'verbose_name_plural': 'Duplas',
                'ordering': ['jogador1__nome'],
            },
        ),
        migrations.CreateModel(
            name='Torneio',
            fields=[
                ('id', shortuuid.django_fields.ShortUUIDField(alphabet=None, length=8, max_length=40, prefix='', primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100)),
                ('data', models.DateField()),
                ('quantidade_times', models.IntegerField(choices=[(4, '4'), (8, '8'), (16, '16')], default=8, verbose_name='Nº de times')),
                ('tipo', models.CharField(choices=[('S', 'Simples'), ('D', 'Duplas')], default='D', help_text='Simples ou Duplas', max_length=1, verbose_name='Tipo de Torneio')),
                ('slug', models.SlugField(unique=True)),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('draw_pairs', models.BooleanField(default=False, help_text='Duplas montadas aleatoriamente ao criar os jogos', verbose_name='Duplas aleatórias')),
                ('inscricao_aberta', models.BooleanField(default=False, help_text='Criar um link para cadastrar jogadores no torneio', verbose_name='Inscrição aberta')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('criado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='torneios_futevolei', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Torneio',
                'verbose_name_plural': 'Torneios',
                'ordering': ['-data', '-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='Jogo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pontos_dupla1', models.IntegerField(blank=True, null=True, verbose_name='Pontos dupla 1')),
                ('pontos_dupla2', models.IntegerField(blank=True, null=True, verbose_name='Pontos dupla 2')),
                ('fase', models.CharField(blank=True, choices=[('FASE 1', 'F1'), ('FASE 2', 'F2'), ('FASE 3', 'F3'), ('FASE 4', 'F4'), ('FASE 5', 'F5'), ('FASE 6', 'F6'), ('FASE 7', 'F7'), ('FASE 8', 'F8')], default='GRUPO 1', max_length=100, null=True, verbose_name='Fase')),
                ('concluido', models.CharField(choices=[('P', '🚫'), ('A', '🎾'), ('C', '✅')], default='P', max_length=2, verbose_name='Status')),
                ('obs', models.TextField(blank=True, help_text='Alguma observação sobre o jogo. Ex: "Dupla 1 WO"', null=True)),
                ('playoff_number', models.SmallIntegerField(blank=True, null=True, verbose_name='Playoff game number')),
                ('playoff_help_text', models.CharField(blank=True, default='', help_text='Ex: 1º G1x2º G2, 1º G2xBYE', max_length=100, verbose_name='Texto de ajuda para o playoff')),
                ('dupla1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dupla1', to='futevolei.dupla', verbose_name='Dupla 1')),
                ('dupla2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dupla2', to='futevolei.dupla', verbose_name='Dupla 2')),
                ('vencedor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='futevolei.dupla', verbose_name='Vencedor')),
                ('torneio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='futevolei.torneio', verbose_name='Torneio')),
            ],
        ),
        migrations.AddField(
            model_name='dupla',
            name='torneio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='duplas', to='futevolei.torneio'),
        ),
    ]
