# Generated by Django 5.1.3 on 2025-03-11 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InputOutput',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('obs', models.TextField()),
                ('type', models.CharField(choices=[('Entrada', 'Entrada'), ('Saída', 'Saída')], default='Entrada', max_length=10)),
            ],
            options={
                'verbose_name': 'Entrada/Saída',
                'verbose_name_plural': 'Entradas/Saídas',
            },
        ),
    ]
