# Generated by Django 5.1.3 on 2025-03-24 12:35

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inputoutput',
            options={'ordering': ('-date',), 'verbose_name': 'Entrada/Saída', 'verbose_name_plural': 'Entradas/Saídas'},
        ),
        migrations.AlterField(
            model_name='inputoutput',
            name='date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Data'),
        ),
        migrations.AlterField(
            model_name='inputoutput',
            name='obs',
            field=models.TextField(verbose_name='Observação'),
        ),
        migrations.AlterField(
            model_name='inputoutput',
            name='type',
            field=models.CharField(choices=[('Entrada', 'Entrada'), ('Saída', 'Saída')], default='Entrada', max_length=10, verbose_name='Entrada e Saída'),
        ),
        migrations.AlterField(
            model_name='inputoutput',
            name='value',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor (R$)'),
        ),
    ]
