# Generated by Django 5.1.3 on 2026-02-09 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PodioDigitalFeatureLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Link de Inscrição',
                'verbose_name_plural': 'Link de Inscrição',
            },
        ),
        migrations.CreateModel(
            name='PodioDigitalFeaturePlanilha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Exportar Planilha',
                'verbose_name_plural': 'Exportar Planilha',
            },
        ),
        migrations.CreateModel(
            name='PodioDigitalOpenGames',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Criar jogos manualmente',
                'verbose_name_plural': 'Criar jogos manualmente',
            },
        ),
    ]
