# Generated by Django 5.1.3 on 2024-12-10 17:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FeriadoPontoFacultativo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('dia', models.IntegerField()),
                ('mes', models.IntegerField()),
                ('ano', models.IntegerField(default=2024)),
            ],
            options={
                'verbose_name': 'Feriado / Ponto facultativo',
                'verbose_name_plural': 'Feriados / Pontos facultativos',
            },
        ),
        migrations.CreateModel(
            name='Escala',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('ativo', models.BooleanField(default=True)),
                ('criado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Plantonista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('ordem_na_lista', models.IntegerField()),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('telefone', models.CharField(blank=True, max_length=20, null=True)),
                ('proximas_ferias', models.DateField(blank=True, null=True)),
                ('dias_de_ferias', models.IntegerField(blank=True, null=True)),
                ('criado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Plantonista',
                'verbose_name_plural': 'Plantonistas',
            },
        ),
        migrations.CreateModel(
            name='Plantao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('turno', models.IntegerField(choices=[(1, 'Manhã'), (2, 'Noite')], default=2)),
                ('data', models.DateField()),
                ('escala', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='escala_de_plantao.escala')),
                ('plantonista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='escala_de_plantao.plantonista')),
            ],
            options={
                'verbose_name': 'Plantão',
                'verbose_name_plural': 'Plantões',
            },
        ),
        migrations.AddField(
            model_name='escala',
            name='plantonistas',
            field=models.ManyToManyField(blank=True, to='escala_de_plantao.plantonista'),
        ),
    ]
