# Generated by Django 5.1.3 on 2024-12-11 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escala_de_plantao', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='escala',
            name='dois_turnos_fds',
            field=models.BooleanField(default=False, help_text='Habilita os dois turnos no fim de semana'),
        ),
    ]
