# Generated by Django 5.1.3 on 2024-12-16 21:31

import shortuuid.django_fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('escala_de_plantao', '0002_escala_dois_turnos_fds'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='feriadopontofacultativo',
            options={'ordering': ('ano', 'mes', 'dia'), 'verbose_name': 'Feriado / Ponto facultativo', 'verbose_name_plural': 'Feriados / Pontos facultativos'},
        ),
        migrations.AlterField(
            model_name='escala',
            name='id',
            field=shortuuid.django_fields.ShortUUIDField(alphabet=None, length=8, max_length=40, prefix='', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='feriadopontofacultativo',
            name='id',
            field=shortuuid.django_fields.ShortUUIDField(alphabet=None, length=8, max_length=40, prefix='', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='plantonista',
            name='id',
            field=shortuuid.django_fields.ShortUUIDField(alphabet=None, length=8, max_length=40, prefix='', primary_key=True, serialize=False),
        ),
    ]
