# Generated by Django 5.1.3 on 2024-12-21 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('escala_de_plantao', '0003_alter_feriadopontofacultativo_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='feriadopontofacultativo',
            options={'verbose_name': 'Feriado / Ponto facultativo', 'verbose_name_plural': 'Feriados / Pontos facultativos'},
        ),
    ]
