# Generated by Django 5.1.3 on 2024-12-31 01:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escala_de_plantao', '0004_alter_feriadopontofacultativo_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='feriadopontofacultativo',
            options={'verbose_name': 'Feriado', 'verbose_name_plural': 'Feriados'},
        ),
        migrations.AddField(
            model_name='plantao',
            name='criado_por',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='escala',
            name='dois_turnos_fds',
            field=models.BooleanField(default=False, help_text='Habilita os dois turnos no fim de semana', verbose_name='Dois turnos no fim de semana'),
        ),
        migrations.AlterField(
            model_name='feriadopontofacultativo',
            name='ano',
            field=models.IntegerField(default=2024, verbose_name='Ano'),
        ),
        migrations.AlterField(
            model_name='feriadopontofacultativo',
            name='mes',
            field=models.IntegerField(verbose_name='Mês'),
        ),
        migrations.AlterField(
            model_name='plantao',
            name='data',
            field=models.DateField(verbose_name='Data'),
        ),
        migrations.AlterField(
            model_name='plantao',
            name='escala',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='escala_de_plantao.escala', verbose_name='Escala'),
        ),
    ]
