# Generated by Django 5.1.3 on 2026-02-17 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escala_de_plantao', '0008_alter_ordemplantonista_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feriadopontofacultativo',
            name='ano',
            field=models.IntegerField(default=2026, verbose_name='Ano'),
        ),
    ]
