JAZZMIN_SETTINGS = {
    'site_title': 'Pódio Digital',
    'site_header': 'Pódio Digital',
    'site_brand': 'Pódio Digital',
    'site_logo': 'images/trophy-adm-new.svg',
    'login_logo': 'images/trophy-adm-new.svg',
    'login_logo_dark': None,
    'site_logo_classes': 'img-circle',
    'site_icon': None,
    'welcome_sign': 'Olá, seja bem-vindo!',
    'see_you_later': 'Até logo!',
    'copyright': 'ALCA Inovações Tecnológicas',
    'custom_css': 'css/custom-theme.css',
    'custom_js': 'js/custom-theme.js',
    'related_modal_active': True,
    # 'changeform_format': 'carousel',
    'topmenu_links': [
        {'name': 'Início',  'url': 'admin:index'},
        {'name': 'Torneios',  'url': 'admin:cup_torneio_changelist', 'permissions': ['cup.view_torneio']},
        {'name': 'Rei/Rainha',  'url': 'admin:bt_league_torneio_changelist', 'permissions': ['bt_league.view_torneio']},
    ],
    'icons': {
        'admin.LogEntry': 'fas fa-book',
        'auth.Group': 'fas fa-users',
        'auth.User': 'fas fa-user',
        'aluguel_quadra.Aluguel': 'fas fa-hand-holding-usd',
        'aluguel_quadra.Quadra': 'fas fa-plus-square',
        'bookstore.Book': 'fas fa-book',
        'bookstore.Genre': 'fas fa-tag',
        'bt_league.Jogador': 'fas fa-users',
        'bt_league.Jogo': 'fas fa-table-tennis-paddle-ball',
        'bt_league.Ranking': 'fas fa-ranking-star',
        'bt_league.Torneio': 'fas fa-medal',
        'bt_cup.Dupla': 'fas fa-user-friends',
        'bt_cup.Jogo': 'fas fa-table-tennis-paddle-ball',
        'bt_cup.Torneio': 'fas fa-trophy',
        'cup.Dupla': 'fas fa-user-friends',
        'cup.Torneio': 'fas fa-trophy',
        'cup.Jogador': 'fas fa-users',
        'cup.Jogo': 'fas fa-table-tennis-paddle-ball',
        'cup.Ranking': 'fas fa-ranking-star',
        'escala_de_plantao.Escala': 'fas fa-sitemap',
        'escala_de_plantao.Plantonista': 'fas fa-users',
        'escala_de_plantao.Plantao': 'fas fa-briefcase',
        'escala_de_plantao.FeriadoPontoFacultativo': 'fas fa-calendar-alt',
        'payments.InputOutput': 'fas fa-hand-holding-usd',
    },
    'default_icon_parents': 'fas fa-chevron-circle-right',
    'default_icon_children': 'fas fa-circle',
    # 'show_ui_builder': True
}

JAZZMIN_UI_TWEAKS = {
    'navbar_small_text': False,
    'footer_small_text': False,
    'body_small_text': False,
    'brand_small_text': False,
    'brand_colour': 'navbar-gray',
    'accent': 'accent-orange',
    'navbar': 'navbar-orange navbar-light',
    'no_navbar_border': True,
    'navbar_fixed': True,
    'layout_boxed': False,
    'footer_fixed': False,
    'sidebar_fixed': True,
    'sidebar': 'sidebar-dark-orange',
    'sidebar_nav_small_text': False,
    'sidebar_disable_expand': False,
    'sidebar_nav_child_indent': False,
    'sidebar_nav_compact_style': False,
    'sidebar_nav_legacy_style': True,
    'sidebar_nav_flat_style': False,
    'theme': 'default',
    'dark_mode_theme': None,
    'button_classes': {
        'primary': 'btn-primary',
        'secondary': 'btn-secondary',
        'info': 'btn-info',
        'warning': 'btn-warning',
        'danger': 'btn-danger',
        'success': 'btn-success'
    }
}
