JAZZMIN_SETTINGS = {
    'site_title': 'Painel de Gestão',
    'site_header': 'Painel de Gestão',
    'site_brand': 'Painel de Gestão',
    'site_logo': 'images/adm.ico',
    'login_logo': 'images/adm.ico',
    'login_logo_dark': None,
    'site_logo_classes': 'img-circle',
    'site_icon': None,
    'welcome_sign': 'Entre com sua conta',
    'copyright': 'ALCA Inovações Tecnológicas',
    'custom_css': 'css/custom-theme.css',
    'custom_js': 'js/custom-theme.js',
    # "related_modal_active": True,
    'topmenu_links': [
        {'name': 'Home',  'url': 'admin:index', 'permissions': ['auth.view_user']},
    ],
    'icons': {
        'admin.LogEntry': 'fas fa-book',
        'auth.Group': 'fas fa-users',
        'auth.User': 'fas fa-user',
        'aluguel_quadra.Aluguel': 'fas fa-hand-holding-usd',
        'aluguel_quadra.Quadra': 'fas fa-plus-square',
        'bookstore.Book': 'fas fa-book',
        'bookstore.Genre': 'fas fa-tag',
        'bt_league.Jogador': 'fas fa-users',
        'bt_league.Torneio': 'fas fa-trophy',
        'bt_cup.Dupla': 'fas fa-user-friends',
        'bt_cup.Torneio': 'fas fa-trophy',
        'escala_de_plantao.Escala': 'fas fa-sitemap',
        'escala_de_plantao.Plantonista': 'fas fa-users',
        'escala_de_plantao.Plantao': 'fas fa-briefcase',
        'escala_de_plantao.FeriadoPontoFacultativo': 'fas fa-calendar-alt',
        'payments.InputOutput': 'fas fa-hand-holding-usd',
    },
    'default_icon_parents': 'fas fa-chevron-circle-right',
    'default_icon_children': 'fas fa-circle',
}

JAZZMIN_UI_TWEAKS = {
    'navbar_small_text': False,
    'footer_small_text': False,
    'body_small_text': False,
    'brand_small_text': False,
    'brand_colour': False,
    'accent': 'accent-lightblue',
    'navbar': 'navbar-dark',
    'no_navbar_border': True,
    'navbar_fixed': True,
    'layout_boxed': False,
    'footer_fixed': False,
    'sidebar_fixed': True,
    'sidebar': 'sidebar-dark-primary',
    'sidebar_nav_small_text': False,
    'sidebar_disable_expand': False,
    'sidebar_nav_child_indent': False,
    'sidebar_nav_compact_style': False,
    'sidebar_nav_legacy_style': True,
    'sidebar_nav_flat_style': False,
    'theme': 'default',
    'dark_mode_theme': None,
    'button_classes': {
        'primary': 'btn-outline-primary',
        'secondary': 'btn-outline-secondary',
        'info': 'btn-outline-info',
        'warning': 'btn-outline-warning',
        'danger': 'btn-outline-danger',
        'success': 'btn-outline-success'
    }
}
