# Generated by Django 5.1.3 on 2024-12-04 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bt_league', '0002_jogador_criado_por'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jogador',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
