# Generated by Django 5.1.3 on 2024-12-04 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bt_league', '0003_alter_jogador_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='torneio',
            name='jogadores',
            field=models.ManyToManyField(blank=True, to='bt_league.jogador'),
        ),
    ]
