# Generated by Django 5.1.3 on 2024-12-21 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bt_league', '0005_alter_jogador_id_alter_torneio_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='jogo',
            name='quadra',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='torneio',
            name='quadras',
            field=models.IntegerField(default=1),
        ),
    ]
