# Generated by Django 5.1.3 on 2025-02-22 22:35

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bt_league', '0007_alter_torneio_ativo'),
    ]

    operations = [
        migrations.AddField(
            model_name='jogador',
            name='ativo',
            field=models.BooleanField(default=True, verbose_name='Ativo'),
        ),
        migrations.AddField(
            model_name='jogador',
            name='criado_em',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
