# Generated by Django 5.1.3 on 2025-03-05 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bt_league', '0008_jogador_ativo_jogador_criado_em'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='jogador',
            options={'ordering': ['nome'], 'verbose_name': 'Jogador', 'verbose_name_plural': 'Jogadores'},
        ),
        migrations.AlterModelOptions(
            name='torneio',
            options={'ordering': ['-data'], 'verbose_name': 'Torneio', 'verbose_name_plural': 'Torneios'},
        ),
        migrations.AlterField(
            model_name='torneio',
            name='quadras',
            field=models.IntegerField(default=1, help_text='Quantidade de quadras para jogos simultâneos'),
        ),
    ]
