# Generated by Django 5.1.3 on 2025-08-10 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bt_league', '0011_jogador_grupo_criador_ranking_grupo_criador_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='torneio',
            options={'ordering': ['-data'], 'verbose_name': 'Campeonato', 'verbose_name_plural': 'Campeonatos'},
        ),
        migrations.AlterField(
            model_name='jogo',
            name='concluido',
            field=models.BooleanField(default=False, verbose_name=''),
        ),
    ]
