# Generated by Django 5.1.3 on 2025-08-19 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bt_league', '0012_alter_torneio_options_alter_jogo_concluido'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jogo',
            name='concluido',
            field=models.CharField(choices=[('P', 'Pendente'), ('A', 'Em Andamento'), ('C', 'Concluído')], default='P', max_length=2, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='torneio',
            name='jogadores',
            field=models.ManyToManyField(blank=True, help_text='O número de jogadores deve ser multiplo de 4.', to='bt_league.jogador'),
        ),
    ]
