# Generated by Django 5.1.3 on 2025-08-28 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bt_league', '0013_alter_jogo_concluido_alter_torneio_jogadores'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jogo',
            name='concluido',
            field=models.CharField(choices=[('P', '❌'), ('A', '⌛'), ('C', '✅')], default='P', max_length=2, verbose_name='Status'),
        ),
    ]
