# Generated by Django 5.1.3 on 2025-09-11 15:02

from django.db import migrations, models
from django.template.defaultfilters import slugify

def populate_slug(apps, schema_editor):
    Torneio = apps.get_model('bt_league', 'Torneio')
    for torneio in Torneio.objects.all():
        if not torneio.slug:
            torneio.slug = f'{slugify(torneio.nome)}_{torneio.id}'
            torneio.save()

class Migration(migrations.Migration):

    dependencies = [
        ('bt_league', '0014_alter_jogo_concluido'),
    ]

    operations = [
        migrations.AddField(
            model_name='torneio',
            name='slug',
            field=models.SlugField(null=True, blank=True, unique=True),
        ),
        migrations.RunPython(populate_slug, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='torneio',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
