# Generated by Django 5.1.3 on 2025-10-27 19:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bt_league', '0016_ranking_slug_alter_jogo_concluido_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jogo',
            name='concluido',
            field=models.CharField(choices=[('P', '🚫'), ('A', '🎾'), ('C', '✅')], default='P', max_length=2, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='jogo',
            name='placar_dupla1',
            field=models.IntegerField(blank=True, null=True, verbose_name='Pontos dupla 1'),
        ),
        migrations.AlterField(
            model_name='jogo',
            name='placar_dupla2',
            field=models.IntegerField(blank=True, null=True, verbose_name='Pontos dupla 2'),
        ),
        migrations.AlterField(
            model_name='torneio',
            name='ranking',
            field=models.ForeignKey(blank=True, help_text='Agrupar torneio em um ranking', null=True, on_delete=django.db.models.deletion.SET_NULL, to='bt_league.ranking'),
        ),
    ]
