# Generated by Django 5.1.3 on 2025-11-17 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bt_league', '0017_alter_jogo_concluido_alter_jogo_placar_dupla1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='torneio',
            name='inscricao_aberta',
            field=models.BooleanField(default=False, help_text='Criar um link para cadastrar jogadores no torneio', verbose_name='Inscrição aberta'),
        ),
    ]
