# Generated by Django 5.1.3 on 2026-02-17 13:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bt_league', '0019_jogador_cpf'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='torneio',
            options={'ordering': ['-data', '-criado_em'], 'verbose_name': 'Campeonato', 'verbose_name_plural': 'Campeonatos'},
        ),
        migrations.AddField(
            model_name='torneio',
            name='n_jogadores',
            field=models.IntegerField(choices=[(4, '4'), (5, '5'), (8, '8'), (12, '12'), (16, '16')], default=8, verbose_name='Número de jogadores'),
        ),
        migrations.AlterField(
            model_name='jogo',
            name='dupla1_jogador1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dupla1_jogador1', to='bt_league.jogador', verbose_name='Jogador 1 dupla 1'),
        ),
        migrations.AlterField(
            model_name='jogo',
            name='dupla1_jogador2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dupla1_jogador2', to='bt_league.jogador', verbose_name='Jogador 2 dupla 1'),
        ),
        migrations.AlterField(
            model_name='jogo',
            name='dupla2_jogador1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dupla2_jogador1', to='bt_league.jogador', verbose_name='Jogador 1 dupla 2'),
        ),
        migrations.AlterField(
            model_name='jogo',
            name='dupla2_jogador2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dupla2_jogador2', to='bt_league.jogador', verbose_name='Jogador 2 dupla 2'),
        ),
    ]
