# Generated by Django 5.1.3 on 2026-03-07 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bt_league', '0020_alter_torneio_options_torneio_n_jogadores_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='torneio',
            name='n_jogadores',
            field=models.IntegerField(choices=[(4, '4'), (5, '5'), (6, '6'), (8, '8'), (9, '9'), (12, '12'), (16, '16')], default=8, verbose_name='Nº jogadores'),
        ),
    ]
